// Comprehensive Vedic Horoscope content data
// All 12 Rashis (zodiac signs) with daily predictions

export interface ZodiacSign {
  id: string;
  name: string;
  nameHindi: string;
  symbol: string;
  element: string;
  ruler: string;
  dateRange: string;
  luckyNumber: number;
  luckyColor: string;
  luckyDay: string;
  compatibility: string;
  dailyPrediction: string;
  careerPrediction: string;
  lovePrediction: string;
  healthPrediction: string;
  financePrediction: string;
  overallRating: number; // 1-5
}

export const zodiacSigns: ZodiacSign[] = [
  {
    id: 'aries',
    name: 'Aries',
    nameHindi: 'मेष (Mesh)',
    symbol: '♈',
    element: 'Fire',
    ruler: 'Mars (Mangal)',
    dateRange: 'Mar 21 – Apr 19',
    luckyNumber: 9,
    luckyColor: 'Red',
    luckyDay: 'Tuesday',
    compatibility: 'Leo, Sagittarius',
    dailyPrediction: 'A day of bold initiatives awaits you. Mars energizes your first house, bringing renewed confidence and leadership opportunities. Trust your instincts and take the leap — the cosmos supports decisive action today. Avoid confrontations in the evening hours.',
    careerPrediction: 'Professional breakthroughs are on the horizon. A superior may notice your exceptional work ethic. Entrepreneurs should expect promising leads from unexpected channels.',
    lovePrediction: 'Romance is in the air for singles. Committed partners will find renewed passion. Express your feelings openly — vulnerability is your strength today.',
    healthPrediction: 'High energy levels throughout the day. Channel excess fire energy through vigorous exercise. Watch your diet — avoid overly spicy foods.',
    financePrediction: 'A moderate day for finances. Avoid impulsive purchases. Long-term investments look favorable, especially in real estate.',
    overallRating: 4,
  },
  {
    id: 'taurus',
    name: 'Taurus',
    nameHindi: 'वृषभ (Vrishabh)',
    symbol: '♉',
    element: 'Earth',
    ruler: 'Venus (Shukra)',
    dateRange: 'Apr 20 – May 20',
    luckyNumber: 6,
    luckyColor: 'Green',
    luckyDay: 'Friday',
    compatibility: 'Virgo, Capricorn',
    dailyPrediction: 'Venus blesses your chart with harmony and abundance. Financial matters take a positive turn, and material comforts are heightened. Focus on building stable foundations — both in career and relationships. Patience is your greatest ally.',
    careerPrediction: 'Steady progress at work. Your reliability will be recognized by management. A collaboration with a colleague may yield excellent results.',
    lovePrediction: 'Emotional stability in relationships. Plan a cozy evening with your partner. Singles may attract someone who values loyalty and depth.',
    healthPrediction: 'Focus on neck and throat wellness. Singing or humming can be therapeutic today. Prioritize quality sleep for optimal vitality.',
    financePrediction: 'Excellent day for savings and investments. A financial opportunity related to agriculture or luxury goods may present itself.',
    overallRating: 5,
  },
  {
    id: 'gemini',
    name: 'Gemini',
    nameHindi: 'मिथुन (Mithun)',
    symbol: '♊',
    element: 'Air',
    ruler: 'Mercury (Budh)',
    dateRange: 'May 21 – Jun 20',
    luckyNumber: 5,
    luckyColor: 'Yellow',
    luckyDay: 'Wednesday',
    compatibility: 'Libra, Aquarius',
    dailyPrediction: 'Mercury activates your communication house, making this an ideal day for negotiations, writing, and networking. Your wit and charm are at their peak. However, avoid scattering your energy across too many projects — focus brings mastery.',
    careerPrediction: 'Excellent day for presentations and pitches. Your communication skills will shine. Consider learning a new skill that complements your career goals.',
    lovePrediction: 'Intellectual connections deepen today. Engage in meaningful conversations with your partner. Singles might connect with someone at a social gathering.',
    healthPrediction: 'Mental wellness takes priority. Practice meditation to calm the restless Gemini mind. Light exercise like walking is highly beneficial.',
    financePrediction: 'Good day for short-term trades. Avoid lending money to acquaintances. Digital ventures show promising returns.',
    overallRating: 4,
  },
  {
    id: 'cancer',
    name: 'Cancer',
    nameHindi: 'कर्क (Kark)',
    symbol: '♋',
    element: 'Water',
    ruler: 'Moon (Chandra)',
    dateRange: 'Jun 21 – Jul 22',
    luckyNumber: 2,
    luckyColor: 'Silver',
    luckyDay: 'Monday',
    compatibility: 'Scorpio, Pisces',
    dailyPrediction: 'The Moon illuminates your domestic sphere, making family matters a priority. Emotional intuition is heightened — trust your inner voice. A nurturing gesture towards loved ones will strengthen bonds immeasurably. Home renovations or redecorating are favored.',
    careerPrediction: 'Creative projects gain momentum. Your emotional intelligence makes you an excellent team player today. Consider exploring roles in counseling or hospitality.',
    lovePrediction: 'Deep emotional connections are favored. Show vulnerability with your partner. Singles may find love through family introductions.',
    healthPrediction: 'Digestive system needs attention. Eat light, warm meals. Emotional healing through journaling is highly recommended.',
    financePrediction: 'Property-related gains are indicated. Avoid risky investments. Savings for family goals are well-aspected.',
    overallRating: 3,
  },
  {
    id: 'leo',
    name: 'Leo',
    nameHindi: 'सिंह (Simha)',
    symbol: '♌',
    element: 'Fire',
    ruler: 'Sun (Surya)',
    dateRange: 'Jul 23 – Aug 22',
    luckyNumber: 1,
    luckyColor: 'Gold',
    luckyDay: 'Sunday',
    compatibility: 'Aries, Sagittarius',
    dailyPrediction: 'The Sun radiates through your sign, amplifying your natural charisma and leadership abilities. Public recognition and creative expression are highlighted. Embrace the spotlight but remain humble — true royalty is in service to others.',
    careerPrediction: 'Leadership roles come naturally today. Your creativity will be the talk of the office. Consider starting that passion project you have been postponing.',
    lovePrediction: 'Grand romantic gestures are favored. Your warmth attracts admirers. Committed Leos should plan something special for their partner.',
    healthPrediction: 'Heart and spine health is important. Practice yoga for spinal alignment. Your vitality is high — use it wisely.',
    financePrediction: 'Generous spending tendencies. While treating others is noble, ensure your own financial security first. Investments in entertainment or arts may pay off.',
    overallRating: 5,
  },
  {
    id: 'virgo',
    name: 'Virgo',
    nameHindi: 'कन्या (Kanya)',
    symbol: '♍',
    element: 'Earth',
    ruler: 'Mercury (Budh)',
    dateRange: 'Aug 23 – Sep 22',
    luckyNumber: 3,
    luckyColor: 'Emerald Green',
    luckyDay: 'Wednesday',
    compatibility: 'Taurus, Capricorn',
    dailyPrediction: 'Mercury sharpens your analytical mind today. This is an excellent day for detailed work, organizing, and health optimization. Your attention to detail will catch errors others miss. Focus on self-improvement rather than criticizing others.',
    careerPrediction: 'Data analysis, editing, and quality control tasks will go exceptionally well. Your meticulous nature earns respect. Health-related careers see positive developments.',
    lovePrediction: 'Show love through practical acts of service. Your partner appreciates the small things you do. Singles should look for someone who values intelligence and kindness.',
    healthPrediction: 'Excellent day for starting a new health regimen. Digestive wellness is important — consider probiotics. Herbal teas can be particularly soothing.',
    financePrediction: 'Budgeting and financial planning are favored. Your analytical skills help you find the best deals. Avoid overthinking investment decisions.',
    overallRating: 4,
  },
  {
    id: 'libra',
    name: 'Libra',
    nameHindi: 'तुला (Tula)',
    symbol: '♎',
    element: 'Air',
    ruler: 'Venus (Shukra)',
    dateRange: 'Sep 23 – Oct 22',
    luckyNumber: 7,
    luckyColor: 'Pink',
    luckyDay: 'Friday',
    compatibility: 'Gemini, Aquarius',
    dailyPrediction: 'Venus graces your chart with beauty and harmony. Relationships of all kinds flourish under this transit. Legal matters may resolve favorably. Your natural diplomacy helps mediate a conflict. Surround yourself with art and aesthetics.',
    careerPrediction: 'Partnerships and collaborations thrive. Your diplomatic skills resolve workplace tensions. Design, law, and relationship counseling careers are highlighted.',
    lovePrediction: 'Romance is at its peak. Balanced, harmonious relationships bring joy. Singles should attend cultural events to meet like-minded individuals.',
    healthPrediction: 'Kidney and lower back health needs attention. Stay hydrated and practice gentle stretching. Beauty treatments and spa days are highly therapeutic.',
    financePrediction: 'Joint finances and partnerships look favorable. Luxury purchases are tempting — exercise moderation. Art investments could appreciate significantly.',
    overallRating: 4,
  },
  {
    id: 'scorpio',
    name: 'Scorpio',
    nameHindi: 'वृश्चिक (Vrishchik)',
    symbol: '♏',
    element: 'Water',
    ruler: 'Mars (Mangal) & Pluto',
    dateRange: 'Oct 23 – Nov 21',
    luckyNumber: 8,
    luckyColor: 'Maroon',
    luckyDay: 'Tuesday',
    compatibility: 'Cancer, Pisces',
    dailyPrediction: 'Transformative energies are at work in your chart. Deep psychological insights surface, offering profound self-understanding. A secret may be revealed — use this knowledge wisely. Meditation and introspection are powerfully healing today.',
    careerPrediction: 'Research and investigative work excel today. Your intensity and focus are unmatched. Consider roles in psychology, finance, or detective work.',
    lovePrediction: 'Passionate and intense connections. Trust issues may surface — address them with honesty. Deep soulful conversations strengthen bonds.',
    healthPrediction: 'Reproductive and eliminatory systems need care. Detox routines are highly beneficial. Emotional release through cathartic activities heals deeply.',
    financePrediction: 'Hidden financial opportunities emerge. Insurance, taxes, and inherited wealth matters are well-aspected. Avoid power struggles over money.',
    overallRating: 3,
  },
  {
    id: 'sagittarius',
    name: 'Sagittarius',
    nameHindi: 'धनु (Dhanu)',
    symbol: '♐',
    element: 'Fire',
    ruler: 'Jupiter (Guru)',
    dateRange: 'Nov 22 – Dec 21',
    luckyNumber: 3,
    luckyColor: 'Purple',
    luckyDay: 'Thursday',
    compatibility: 'Aries, Leo',
    dailyPrediction: 'Jupiter expands your horizons today — literally and figuratively. Travel plans solidify, and higher learning opportunities present themselves. Your optimistic spirit inspires those around you. Philosophical discussions bring profound insights. Share your wisdom generously.',
    careerPrediction: 'International opportunities beckon. Teaching, publishing, and travel-related careers see growth. Your enthusiasm is contagious — lead by inspiration.',
    lovePrediction: 'Adventure-loving connections thrive. Plan an outdoor date or travel together. Singles may find romance while exploring new territories.',
    healthPrediction: 'Thigh and liver health need attention. Outdoor activities boost both physical and mental wellness. Moderate alcohol consumption.',
    financePrediction: 'Expansive financial outlook. International investments may be profitable. Avoid overextending credit. Donations bring karmic blessings.',
    overallRating: 5,
  },
  {
    id: 'capricorn',
    name: 'Capricorn',
    nameHindi: 'मकर (Makar)',
    symbol: '♑',
    element: 'Earth',
    ruler: 'Saturn (Shani)',
    dateRange: 'Dec 22 – Jan 19',
    luckyNumber: 4,
    luckyColor: 'Dark Brown',
    luckyDay: 'Saturday',
    compatibility: 'Taurus, Virgo',
    dailyPrediction: 'Saturn rewards your discipline and hard work today. Career advancements are well-starred, especially for those who have put in consistent effort. Structure and planning lead to tangible results. Authority figures take notice of your reliability.',
    careerPrediction: 'Promotions and recognitions are possible. Your management skills are at their peak. Government and corporate careers see steady advancement.',
    lovePrediction: 'Mature, committed relationships deepen. Show your softer side to your partner. Singles may attract an older or more established individual.',
    healthPrediction: 'Bone and joint health require attention. Calcium-rich foods and weight-bearing exercises are recommended. Set healthy boundaries to prevent burnout.',
    financePrediction: 'Conservative financial strategies pay off. Real estate and long-term bonds are excellent choices. Your frugality builds substantial wealth over time.',
    overallRating: 4,
  },
  {
    id: 'aquarius',
    name: 'Aquarius',
    nameHindi: 'कुम्भ (Kumbh)',
    symbol: '♒',
    element: 'Air',
    ruler: 'Saturn (Shani) & Rahu',
    dateRange: 'Jan 20 – Feb 18',
    luckyNumber: 11,
    luckyColor: 'Electric Blue',
    luckyDay: 'Saturday',
    compatibility: 'Gemini, Libra',
    dailyPrediction: 'Innovation and progressive thinking define your day. Humanitarian impulses are strong — channel them into community service. Technology and social media may bring unexpected opportunities. Embrace your uniqueness — the world needs your unconventional perspective.',
    careerPrediction: 'Technology and innovation roles thrive. Your forward-thinking ideas gain traction. Networking brings valuable connections. Consider freelancing or consulting.',
    lovePrediction: 'Friendship-based romance is highlighted. Intellectual stimulation matters more than grand gestures. Singles may connect through online platforms or social causes.',
    healthPrediction: 'Circulatory and ankle health needs attention. Innovative wellness approaches like cryotherapy or biohacking appeal to you. Stay grounded through nature walks.',
    financePrediction: 'Cryptocurrency and tech investments may yield gains. Group financial ventures are favored. Donate to causes you believe in — abundance flows when shared.',
    overallRating: 3,
  },
  {
    id: 'pisces',
    name: 'Pisces',
    nameHindi: 'मीन (Meen)',
    symbol: '♓',
    element: 'Water',
    ruler: 'Jupiter (Guru) & Neptune',
    dateRange: 'Feb 19 – Mar 20',
    luckyNumber: 12,
    luckyColor: 'Sea Green',
    luckyDay: 'Thursday',
    compatibility: 'Cancer, Scorpio',
    dailyPrediction: 'Jupiter and Neptune infuse your day with spirituality and creative inspiration. Dreams may carry prophetic messages — keep a dream journal. Artistic pursuits are deeply fulfilling. Compassion flows naturally — but remember to establish healthy boundaries.',
    careerPrediction: 'Creative and spiritual careers flourish. Music, art, photography, and healing professions see growth. Your intuition guides you to the right decisions.',
    lovePrediction: 'Deeply romantic and soulful connections. Poetry, music, and shared spiritual experiences deepen bonds. Singles may experience love at first sight.',
    healthPrediction: 'Feet and immune system health are important. Swimming and water therapies are excellent. Avoid escapist tendencies — face challenges with courage.',
    financePrediction: 'Intuitive financial decisions serve you well. Charitable giving brings unexpected returns. Avoid unclear financial agreements — read the fine print.',
    overallRating: 4,
  },
];

export function getSignByName(name: string): ZodiacSign | undefined {
  return zodiacSigns.find(s => s.name.toLowerCase() === name.toLowerCase());
}

export function getTodayDate(): string {
  return new Date().toLocaleDateString('en-IN', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}
